### PR TITLE
audits for rhels 7 updated to CIS version 2.0 

### PR DESCRIPTION
**Pull request by toomanyonhere**
This is most of the checks, in the older format.  There are a few checks that need the new command format so they aren't included here.

### CODE REVIEW

**Comment by basepi** [comment]
Perfect! I also added the command module so we can start working on those: https://github.com/HubbleStack/Nova/pull/141

**Comment by toomanyonhere** [comment]
Cool, I will start on that on Monday.  I may start on doing level 2 checks first and do that with the new command modules.  since there is only about 30 checks to do for level 2.

**Comment by basepi** [comment]
We'll take any help we can get!

**Comment by basepi** [comment]
Can you please remove the dot in the filename? The nova topfile feature uses dots as directory separators (much like salt does) so dots in profile filenames will cause problems.

I wonder if we should name it something like this:

```
cis2-centos-7-l1-scored.yaml
```

So that the v1 and v2 versions will sort themselves. We could put a note at the top of the profile noting that it's 2.0, and then when we update to 2.1 we can update that note. I don't think we want to maintain different dot releases of CIS profiles.

@cedwards any thoughts on naming here?

**Comment by cedwards** [comment]
`cis-centos-7-l1-scored-v2.yaml`, `cis-centos-7-l1-scored-v1.yaml`, etc..

**Comment by toomanyonhere** [comment]
I just removed that file out of the tree, since it was still the same as the original file. I'll get it to actually be CIS v2.0 and then put it back in the tree,  with the file for the Level 2 checks.  
When I do I'll use the naming scheme that Christer suggested. I think that make sense for places that don't want to immediately switch CIS standards.

**Comment by toomanyonhere** [comment]
I got bored during a meeting, since the Red Hat server, Red Hat Workstation, CentOS are almost Identical, for Level 1, I did the rhelw-7-l1-scored and centos-7-scored-v2 files.

**Comment by cedwards** [comment]
thank you!

**Pull request merged**
