### PR TITLE
Adding reason for failing stats

### PR DESCRIPTION
**Pull request by gmiu**
The output looks like this:

```
local:
    ----------
    Compliance:
        78%
    Failure:
        |_
          ----------
          description:
              /etc/cron.d must be owned by root and must have permissions 700
          gid:
              0
          group:
              root
          mode:
              700
          module:
              stat
          name:
              /etc/cron.d
          reason:
              ----------
              mode:
                  ----------
                  current:
                      755
                  expected:
                      700
          tag:
              CIS-6.1.9
          uid:
              0
          user:
              root
```

### CODE REVIEW

**Comment by cedwards** [comment]
This is going to make the output _super_ verbose. Can this be used via a kwargs flag, or maybe cut down to just the bare minimum required to show the reason.

**Comment by gmiu** [comment]
The kwargs flag should bring modifications also in `hubble.py`. Maybe @basepi has something to say about this. 

Also, I could create a string for reason. I just have to think of its format (in case all `mode`, `uid`, `user`, `gid` and `group` fail - I guess it will be longer). I could also cut the `gid` / `group` and `uid` /  `user` since both ways reflect the same thing.

**Comment by gmiu** [comment]
Something like: `expected 600 0 0 / found 644 0 0`.

Later edit: or `expected mode:600 uid:0 gid:0 / found mode:644 uid:0 gid:0`.

**Comment by gmiu** [comment]
```
local:
    ----------
    Compliance:
        78%
    Failure:
        |_
          ----------
          description:
              /etc/cron.d must be owned by root and must have permissions 700
          diff:
              expected  gid 0  uid 0  mode 700  / found  gid 61572  uid 61572  mode 755 
          gid:
              0
          group:
              root
          mode:
              700
          module:
              stat
          name:
              /etc/cron.d
          tag:
              CIS-6.1.9
          uid:
              0
          user:
              root
```

@cedwards, what about this?

**Comment by cedwards** [comment]
Can you show me an example of _just_ displaying the `diff` key:value? The rest still seems verbose.

**Comment by cedwards** [comment]
+1

**Comment by basepi** [comment]
I think it's fine. Most of the time you won't be running with verbose=True. And most people will probably be running with show_success=False and won't have many failures once they fix them. So you see a failure, run the audit again with verbose if you want to see exactly how the failure happened.

I don't think it makes sense to show the diff in non-verbose mode. So either we keep it super-verbose, pull information out of verbose mode, or add a half-verbose mode. I vote for just keeping it super-verbose, since this will only be used sometimes.

**Comment by gmiu** [comment]
I think it's better how it is now: show the diff in verbose mode. I still don't like how the diff string looks though... Any suggestions, @basepi?

**Comment by basepi** [comment]
I think the first way you did it might be better. I don't think @cedwards was worried about the actual diff being verbose, but rather was worried about all the rest of verbose mode.

**Comment by gmiu** [comment]
@cedwards, @basepi, so should I come back to the first way?

**Comment by basepi** [comment]
That's my vote. @cedwards can comment as well.

**Comment by cedwards** [comment]
The first way is good.

**Comment by gmiu** [comment]
@basepi, should I deal with the conflicts here?

**Comment by basepi** [comment]
Ah yes, sorry for that. I moved the modules into `hubblestack_nova/modules/`. You can try rebasing, but with the rename you might have to manually port your fixes over.

**Pull request merged**
