### PR TITLE
Move the nova modules into their own directory

### PR DESCRIPTION
**Pull request by basepi**
Further organization of the profiles can happen later, but I want to make this change now to clean things up a bit.

### CODE REVIEW

**Comment by cedwards** [comment]
Looks good.

**Comment by gmiu** [comment]
@basepi, I'd suggest renaming this directory into `plugins`.

**Comment by basepi** [comment]
I personally tend to call them modules when I talk about them. We should standardize the term.

**Comment by gmiu** [comment]
So which one should it be?

**Comment by cedwards** [comment]
modules

**Pull request merged**
