### PR TITLE
Better error reporting, and don't show empty keys in results

### PR DESCRIPTION
**Pull request by basepi**
I now report errors if you pass in a profile which doesn't match anything.

I also noticed during the demo today that hosts which ran no checks still showed a "Failure" key. So now I'm popping any empty keys in the results dictionary.

### CODE REVIEW

**Comment by gmiu** [comment]
I wouldn't see it quite as an error if the profile didn't match. But it doesn't really matter anyway. I think it a good idea.

**Comment by basepi** [comment]
The place where it's most valuable is in topfiles. Previously, if I misspelled a profile there, it would just be skipped, reporting no errors.

**Comment by gmiu** [comment]
Yeah, you're right. I keep forgetting about the topfiles.

**Comment by gmiu** [comment]
Shouldn't this apply also in this case? 

```
# salt-call grains.get osfinger
local:
    CentOS-6
# salt-call hubble.audit CIS-CentOS-7-L1-scored
[INFO    ] Caching directory u'hubblestack_nova/' for environment 'base'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/CIS-CentOS-6-L1-scored.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/CIS-CentOS-7-L1-scored.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/CIS-Debian-8-L1-scored.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/CIS-RHELS-6-L1-scored.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/CIS-Ubuntu-14.04-L1-scored.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/CIS.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/README.rst'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/control_key_test.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/cve_scan.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/cve_scan.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/firewall.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/grep.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/netstat.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/pkg.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/pkgng_audit.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/pkgng_audit.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/sample_firewall.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/service.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/stat.py'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/stat.yaml'
[INFO    ] Fetching file from saltenv 'base', ** done ** u'hubblestack_nova/sysctl.py'
local:
    ----------
```

**Comment by cedwards** [comment]
+1

**Comment by basepi** [comment]
@avb76 No. It matched a file. The fact that that file didn't have any checks relevant to the host is a separate issue (and obvious from the empty return).

**Comment by basepi** [comment]
If the return is completely empty I suppose we could add a message "No checks matched this host" or something.

**Comment by gmiu** [comment]
Oh, I wrongly assumed that you were talking about matchings the checks, since you brought up popping any empty keys in the results dict. I guess that message for no matching checks would be useful. We should add it.

**Comment by basepi** [comment]
@avb76 I added another commit with the message.

**Pull request merged**
