### PR TITLE
Add Amazon Linux 2014.09 CIS 1.0.0 profile

### PR DESCRIPTION
**Pull request by zxjinn**
Also updated some misc items in CentOS6 1.0.0 profile, which I copied for the AL profile

### CODE REVIEW

**Comment by cedwards** [comment]
Thanks @zxjinn . We'll want to rename the file to match the existing standard, but otherwise looks good.

Is this just a direct port from the CentOS-6 profile, or have these tags been updated to match the upstream CIS for Amazon AMI?

**Comment by zxjinn** [comment]
What would you like the file to be called?

I copied the Cent6 profile, then ran through it (20-30 min) and made sure the sections matched up in the [AL benchmark document](https://benchmarks.cisecurity.org/tools2/linux/CIS_Amazon_Linux_2014.09_Benchmark_v1.0.0.pdf). Here is the diff of the two files with all the `CentOS-6` vs `Amazon Linux AMI-2014` lines removed:

``` diff
97c97
<             tag: 'CIS-4.5.3'
---
>             tag: 'CIS-4.4.3'
105c105
<             tag: 'CIS-4.5.5'
---
>             tag: 'CIS-4.4.5'
362,368d361
<   exec_shield:
<     data:
<       CentOS-6:
<       - kernel.exec-shield:
<           match_output: '1'
<           tag: CIS-1.6.2
<     description: Configure ExecShield (Scored)
408c401
<           tag: CIS-1.6.3
---
>           tag: CIS-1.6.2
```

**Comment by cedwards** [comment]
Awesome. Thanks for taking the time to do that.

Let's go with: `cis/amazon-201409-level-1-scored-v1-0-0.yaml`

If @basepi will +1, we'll merge it.

**Comment by basepi** [comment]
I'm cool with that name. I just don't want spaces.

**Comment by basepi** [comment]
@cedwards Are you going to rename these yourself? The current filenames have spaces in them

**Comment by zxjinn** [comment]
Do you want me to make a new PR with the fixed name?

I see that you merged then reverted it, presumably because the filename hadn't been changed yet.

**Comment by cedwards** [comment]
Sorry. Yes, I merged after confirming the name but before waiting for the
rename. Can you update / submit the PR with the new name? Thanks.

**Comment by zxjinn** [comment]
Can do, look for it tomorrow

**Pull request merged**
